name: "Policy Terraform Plan"

# Trigger when a pull request is received
on:
  pull_request:
    branches:
      - main

jobs:
  terraform-plan:
    name: "Terraform Plan"
    env:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      
    runs-on: ubuntu-latest
    steps:
      # Checkout the code
      # Marketplace: https://github.com/marketplace/actions/checkout
      - name: "Setup - Checkout"
        uses: actions/checkout@v2.1.0

      # Downloads a specific version of Terraform CLI and adds it to PATH
      # Marketplace: https://github.com/marketplace/actions/hashicorp-setup-terraform
      - name: "Setup - Terraform CLI"
        uses: hashicorp/setup-terraform@v1

      # Init pulls credentials from the .aws/credentials file by default
      - name: "Run - Terraform Init"
        run: |
          cd policy/
          terraform init -input=false

      # Note: Color is disabled to prevent messy characters from appearing in the pull request comment
      - name: "Run - Terraform Plan"
        run: |
          cd policy/
          terraform plan \
            -var 'client_id=${{ secrets.ARM_CLIENT_ID }}' \
            -var 'client_secret=${{ secrets.ARM_CLIENT_SECRET }}' \
            -var 'tenant_id=${{ secrets.ARM_TENANT_ID }}' \
            -var 'subscription_id=${{ secrets.ARM_SUBSCRIPTION_ID }}' \
            -input=false -no-color