name: "Policy Terraform Apply"

# Trigger when commits are pushed to the master branch
on:
  push:
    branches:
      - main

jobs:
  terraform-plan:
    name: "Terraform Apply"
    env:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      
    runs-on: ubuntu-latest
    steps:
      # Checkout the code
      # Marketplace: https://github.com/marketplace/actions/checkout
      - name: "Setup - Checkout"
        uses: actions/checkout@v2.1.0
      
      # Downloads a specific version of Terraform CLI and adds it to PATH
      # Marketplace: https://github.com/marketplace/actions/hashicorp-setup-terraform
      - name: "Setup - Terraform CLI"
        uses: hashicorp/setup-terraform@v1

      # Login to Azure
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: '{"clientId":"${{ secrets.ARM_CLIENT_ID }}","clientSecret":"${{ secrets.ARM_CLIENT_SECRET }}","subscriptionId":"${{ secrets.ARM_SUBSCRIPTION_ID }}","tenantId":"${{ secrets.ARM_TENANT_ID }}"}'

      # Init setup modules and providers
      - name: "Run - Terraform Init"
        run: |
          cd policy/
          terraform init -input=false

      # Auto-approve prevents the requirement of human interaction
      - name: "Run - Terraform Apply"
        run: |
          cd policy/
          terraform apply \
            -var 'client_id=${{ secrets.ARM_CLIENT_ID }}' \
            -var 'client_secret=${{ secrets.ARM_CLIENT_SECRET }}' \
            -var 'tenant_id=${{ secrets.ARM_TENANT_ID }}' \
            -var 'subscription_id=${{ secrets.ARM_SUBSCRIPTION_ID }}' \
            -input=false -auto-approve